language: java
os: osx
osx_image: xcode9.3

cache:
  directories:
  - $HOME/.m2
  - $HOME/.leelaz

install:
  - sh scripts/make-leelaz.sh
  - sh scripts/download-network.sh

script:
  - mvn test
  - mvn com.coveo:fmt-maven-plugin:check
